create database pizza_sales_prac

select * from order_details
select * from orders
select * from pizza_types
select * from pizzas

-- Table names and columns in the dataset
--order_details -->     order_details_id, order_id, pizza_id, quantity
--orders -->            order_id, date, time
--pizza_types -->       pizza_type_id, name, category, ingredients
--pizzas -->            pizza_id, pizza_type_id, size, price


--1. List all unique pizza categories that were ever ordered.
select distinct pt.category, od.order_id  from pizza_types pt join pizzas p 
on pt.pizza_type_id = p.pizza_type_id
join order_details od 
on p.pizza_id = od.pizza_id

--2. Find the total quantity ordered for each pizza type.
select pt.category, sum(od.quantity) as total_quantity_ordered 
from pizza_types pt join pizzas p 
on pt.pizza_type_id = p.pizza_type_id
join order_details od on p.pizza_id = od.pizza_id
group by pt.category

--3. Which pizza category had the highest total sales amount?
select top 1 pt.category, round(sum(p.price*od.quantity),2) as total_sales_amount
from pizza_types pt join pizzas p
on pt.pizza_type_id = p.pizza_type_id 
join order_details od on p.pizza_id = od.pizza_id
group by  pt.category
order by sum(p.price*od.quantity) desc

--4. Show the top 5 most frequently ordered pizzas.
select top 5 pt.name, count(od.order_id) as pizzas_ordered
from pizza_types pt join pizzas p
on pt.pizza_type_id = p.pizza_type_id 
join order_details od on
p.pizza_id = od.pizza_id
group by pt.name
order by count(od.order_id) desc

--5. List all orders where more than 10 pizzas were ordered in total.
select order_id, sum(quantity) as total_pizzas_ordered
from order_details group by order_id
having sum(quantity) > 10
	
--6. Find the total revenue generated by each pizza size.
select p.size, round(sum(p.price*od.quantity),2) as total_revenue
from pizzas p join order_details od
on p.pizza_id = od.pizza_id
group by p.size

--7. What is the average order value per order?
select od.order_id, round(AVG(od.quantity* p.price),2) as avg_ordervalue
from order_details od join pizzas p
on od.pizza_id = p.pizza_id
group by od.order_id

--8. Show daily total sales, sorted by date in descending order.
select date, count(order_id) as total_sales from orders
group by date
order by date desc

--9. Which day had the highest number of pizzas sold?
select top 1 datename(weekday,o.date) as day, sum(od.quantity) as pizzas_ordered
from order_details od join orders o
on od.order_id = o.order_id
group by datename(weekday,o.date)
order by sum(od.quantity) desc

--10. Find total revenue per pizza type, only for "Veggie" category.
select pt.name, round(sum(p.price*od.quantity),2) as total_revenue
from pizza_types pt join pizzas p
on pt.pizza_type_id = p.pizza_type_id
join order_details od on p.pizza_id = od.pizza_id
where pt.category = 'Veggie'
group by pt.name

--11. Count how many orders were placed each hour.
select  DATEPART(hour,time) as hours, count(order_id) as orders_placed
from orders
group by DATEPART(hour,time)
order by hours

--12. List all pizzas that were never ordered.
select pt.name from pizza_types pt left join pizzas p 
on pt.pizza_type_id = p.pizza_type_id left join 
order_details od on p.pizza_id = od.pizza_id
where od.order_id is null

--13. Show the average number of pizzas ordered per order per category.
select od.order_id, pt.category,avg(od.quantity) as avg_pizza_ordered
from pizza_types pt join pizzas p
on pt.pizza_type_id = p.pizza_type_id 
join order_details od on
od.pizza_id = p.pizza_id
group by od.order_id, pt.category
order by od.order_id

--14. Find the top 3 earning pizza types.
select top 3 pt.name, sum(od.quantity*p.price) as Total_revenue
from pizza_types pt join pizzas p
on pt.pizza_type_id = p.pizza_type_id
join order_details od 
on od.pizza_id = p.pizza_id
group by pt.name
order by Total_revenue desc 

--15. List total revenue per order, but only show those orders where revenue > $300.
select od.order_id, sum(od.quantity*p.price) as Total_revenue
from pizzas p join order_details od
on p.pizza_id = od.pizza_id
group by od.order_id
having sum(od.quantity*p.price) > 300






